Repository thoth-station/buildlog-parser, pull requests merged in 2020-06, with the labels that each got.

#1 Initial project import
  CHANGELOG.md
  Pipfile
  Pipfile.lock
  README.md
  README.rst
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  requirements.txt
  setup.py
  tests/base.py
  tests/data/sample
  tests/data/sample_error
  tests/test_parsing.py
  thoth-buildlog-parser
  thoth/buildlog_parser/__init__.py
  thoth/buildlog_parser/cli.py
  thoth/buildlog_parser/exceptions.py
  thoth/buildlog_parser/parsing.py
  thoth/buildlog_parser/py.typed
Labels: do-not-merge/needs-rebase, do-not-merge/work-in-progress, size/XXL

#8 Run pytest-mypy
  Pipfile
  Pipfile.lock
  mypy.ini
  setup.py
  tests/data/success_adviser_failed/result.json
  tests/test_parsing.py
  thoth/buildlog_parser/cli.py
  thoth/buildlog_parser/exceptions.py
  thoth/buildlog_parser/parsing.py
Labels: size/L

#6 Prefix environment variables with component name
  thoth/buildlog_parser/cli.py
Labels: approved, size/S

#11 Automatic update of dependency thoth-common from 0.13.12 to 0.13.13
  Pipfile.lock
Labels: approved, bot, size/M

#12 Fix environment variable name
  thoth/buildlog_parser/cli.py
Labels: approved, size/XS
