Repository thoth-station/buildlog-parser, pull requests merged in 2020-11, with the labels that each got.

#22 Release of version 0.0.1
  CHANGELOG.md
  thoth/buildlog_parser/__init__.py
Labels: approved, bot, size/S

#19 Automatic update of dependency pytest from 5.4.3 to 6.1.2
  Pipfile.lock
Labels: approved, bot, size/L

#21 Automatic update of dependency pytest-mypy from 0.6.2 to 0.8.0
  Pipfile.lock
Labels: approved, bot, size/XS

#20 Automatic update of dependency pytest-timeout from 1.4.1 to 1.4.2
  Pipfile.lock
Labels: approved, bot, size/XS

#18 Automatic update of dependency attrs from 19.3.0 to 20.3.0
  Pipfile.lock
Labels: approved, bot, size/S

#16 Automatic update of dependency thoth-common from 0.14.1 to 0.20.4
  Pipfile.lock
Labels: approved, bot, size/XS

#25 port to python 38
  .aicoe-ci.yaml
  .thoth.yaml
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#26 compliant with the pre-commit hooks
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  .pre-commit-config.yaml
  .zuul.yaml
  MANIFEST.in
  mypy.ini
  setup.py
  tests/data/success_adviser_failed/result.json
  tests/test_parsing.py
  thoth/buildlog_parser/__init__.py
  thoth/buildlog_parser/cli.py
  thoth/buildlog_parser/parsing.py
Labels: approved, size/L

#27 update .aicoe-yaml
  .aicoe-ci.yaml
Labels: approved, size/XS
