Repository thoth-station/buildlog-parser, pull requests merged in 2022-03, with the labels that each got.

#37 updating pre-commit protocol and aicoe build-strategy
  .aicoe-ci.yaml
  .pre-commit-config.yaml
Labels: size/XS

#33 Update pyproject.toml to use Python 3.8
  pyproject.toml
Labels: approved, size/XS, lifecycle/stale

#38 Automatic update of base-image in CI
  .aicoe-ci.yaml
Labels: approved, size/XS, ok-to-test
